services:
  postgres-db:
    container_name: diary
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: diary_dev
      POSTGRES_PASSWORD: secure-p@sswords-R-long
      POSTGRES_DB: diary
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5428:5432"
volumes:
  postgresql_data:
    driver: local